name: Label User-Story with Epic

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue body
        run: |
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Extract epic label
        run: |
          epic_label=$(awk 'BEGIN{RS=""; FS="\n# Epic Label"} $2 ~ /[^[:space:]]/{print $2}' <<< "${{ github.event.issue.body }}")
          echo "Epic Label: $epic_label"
      - name: Add epic label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: ${{ github.event.issue.number }},
              labels: ["${epic_label}"]
            })
