name: Label Epic

on:
  issues:
    types:
      - opened

jobs:
  label-epic:
    runs-on: ubuntu-latest

    steps:
    - name: Check if Epic Label Provided
      id: check_label
      run: echo "Epic Label :: $(grep -oP '(?<=epic_label: ).*' ${{ github.event.issue.body }} || echo "")"
      
    - name: Apply Epic Label
      if: steps.check_label.outputs.EpicLabel
      run: |
        epic_label="$(grep -oP '(?<=epic_label: ).*' ${{ github.event.issue.body }} || echo "")"
        echo "Applying Epic Label: $epic_label"
        gh issue add-label "${{ github.event.issue.number }}" "$epic_label"
